codobj.o: gcc -c codobj.c
core.o : gcc -c core.c
ct.o : gcc -c ct.c
dicoetiq.o : gcc -c dicoetiq.c
dicoires.o : gcc -c dicoires.c
exec.o : gcc -c exec.c
hach.o : gcc -c hach.c
instruct.o : gcc -c instruct.c
listprog.o : gcc -c listprog.c
load.o : gcc -c load.c
mars.o : gcc -c mars.c
msgerr.o : gcc -c msgerr.c
stat.o : gcc -c stat.c
tradfic.o : gcc -c tradfic.c
tradlig.o : gcc -c tradlig.c
traitarg.o : gcc -c traitarg.c
visu.o : gcc -c visu.c

all:  ${MAKE} -o main codobj.o core.o ct.o dicoetiq.o dicoires.o exec.o hach.o instruct.o listprog.o load.o mars.o msgerr.o stat.o tradfic.o tradlig.o traitarg.o visu.o

/*all : ${MAKE} main*/   